{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-settings-api",
    "version": "8.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.3.0.jar",
          "url": "gradle-settings-api-8.3.0.jar",
          "size": 9856,
          "sha512": "0fe122ea267ab80cf411fa583a763e2428cd753db4321e6b1a8b51029e661ade6c3ea58e47a0acc98bf14fe27997ebb48b2cea7f809318118ba274daa897b9a8",
          "sha256": "3df4a3d8947ca5e7f1bdeef99969b49e3a1a0d25c776d2c86100741274186f73",
          "sha1": "af31c9c7fe0add111cd45a7ceb2bd7a4d8db143b",
          "md5": "e7a889018c86614cfd7c5aea521142cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-settings-api-8.3.0.jar",
          "url": "gradle-settings-api-8.3.0.jar",
          "size": 9856,
          "sha512": "0fe122ea267ab80cf411fa583a763e2428cd753db4321e6b1a8b51029e661ade6c3ea58e47a0acc98bf14fe27997ebb48b2cea7f809318118ba274daa897b9a8",
          "sha256": "3df4a3d8947ca5e7f1bdeef99969b49e3a1a0d25c776d2c86100741274186f73",
          "sha1": "af31c9c7fe0add111cd45a7ceb2bd7a4d8db143b",
          "md5": "e7a889018c86614cfd7c5aea521142cb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.3.0-javadoc.jar",
          "url": "gradle-settings-api-8.3.0-javadoc.jar",
          "size": 261,
          "sha512": "f9cf8929392a518070545fe21ea247f1507c7014b77f9409965aa8e7aaf10fb69e132165083fba61549d36d7fbab89a402e8ee139fc6359d90577fd961787ef3",
          "sha256": "2f975502282b58973b46c33753ef9a199efad72cd3cd2eefa7cff1069b61771e",
          "sha1": "f7353ec267a336b8a6f24c866d5b2da0114338cd",
          "md5": "3f6b80c06815efa437e87eaf6dbe791d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.3.0-sources.jar",
          "url": "gradle-settings-api-8.3.0-sources.jar",
          "size": 9407,
          "sha512": "2f65546d8a7a92e38d370eaa0c0759b474eb6bfa4dd129987d134beb2d8a0d9ffef74e0ae67fb4cd421d4ac79554b94376ddf7b5d72644ae49407f6cc5bc672e",
          "sha256": "1b44b0c03d94f756990d850ce318ddcc3b87315bcdce0038d690f4f815c84f83",
          "sha1": "8c3eb2e2b939ef1d9f8262135e14eb1c2612f563",
          "md5": "d4a5007ba20a0da755f1512e9d2b1ec7"
        }
      ]
    }
  ]
}
