{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.3.0"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.3.0.jar",
          "url": "builder-8.3.0.jar",
          "size": 13496424,
          "sha512": "f1f8fd4c1bee4b67c7d401d885d7b2fa597997d689f2b1c3d35ea695866cc2e2524045d28ab5a184ecf6952727c1781a81bd851a0d422a51a8d17e87dc000374",
          "sha256": "88b5a476fb1433ef73de51bc233bba890977e8692393353d0c192e2e090fcd80",
          "sha1": "8e1c898e72837e1e5c74f6f4bf7c37ce838b57a9",
          "md5": "160331222b191b383428dc00c7007e4a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.3.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.3.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.3.0"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.3.0"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.3.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.3.0"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.67"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.67"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.3.0"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.3.0.jar",
          "url": "builder-8.3.0.jar",
          "size": 13496424,
          "sha512": "f1f8fd4c1bee4b67c7d401d885d7b2fa597997d689f2b1c3d35ea695866cc2e2524045d28ab5a184ecf6952727c1781a81bd851a0d422a51a8d17e87dc000374",
          "sha256": "88b5a476fb1433ef73de51bc233bba890977e8692393353d0c192e2e090fcd80",
          "sha1": "8e1c898e72837e1e5c74f6f4bf7c37ce838b57a9",
          "md5": "160331222b191b383428dc00c7007e4a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.3.0-javadoc.jar",
          "url": "builder-8.3.0-javadoc.jar",
          "size": 400793,
          "sha512": "f92c138aae6ffd930d26ab4e5ec7e0cad2d890f039331be7b8fd069fdde73ef299279ec49a6743c9d2d7ba267a0af7374ea1416cbc332c98642b7f8d156561fc",
          "sha256": "54661e3c1b744f09ed967ce0456beaba30cb50e89c106acec5fb33d2dca83cb6",
          "sha1": "60f69d6af1f5ac908e2eade17945bc4fc0f103b1",
          "md5": "f478b471367f5c9b312c05db6debf8cd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.3.0-sources.jar",
          "url": "builder-8.3.0-sources.jar",
          "size": 282328,
          "sha512": "8d868c9aa10d997f760cc749590ce8d360aff43d6bffa758abacf48f74cd0e0920536596732b59624a8bf9129c08617f4abd8c06a555a2184b24bf1e8a13b8a3",
          "sha256": "f98b5aef99212e67bc182e38575c045f5c188a6c88b22eb0991b3f5eebec6da9",
          "sha1": "5f16515c528990c62ff0a973d3f2510f65493283",
          "md5": "2232a8ecd74db4995c522e8f82510a00"
        }
      ]
    }
  ]
}
