{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-runtime",
    "version": "8.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-runtime-8.3.1.aar",
          "url": "databinding-runtime-8.3.1.aar",
          "size": 60987,
          "sha512": "545ac4793600020166c6da2011e75e4e089ea601ba037a12ce2fb54ed812e752930e2dd9a4d3af332226263033ef2a32b7885f95f46edf9d707fbc1dd144cd26",
          "sha256": "83302b36c86764d9e06a5072ed2a777ccd5fab5563302a9aa161d6e503685e34",
          "sha1": "af8b58298ba6ffc4e4354ed53c952d5376e4c009",
          "md5": "7a36abec7735548d6e2cb1d4c31882fa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-runtime-8.3.1.aar",
          "url": "databinding-runtime-8.3.1.aar",
          "size": 60987,
          "sha512": "545ac4793600020166c6da2011e75e4e089ea601ba037a12ce2fb54ed812e752930e2dd9a4d3af332226263033ef2a32b7885f95f46edf9d707fbc1dd144cd26",
          "sha256": "83302b36c86764d9e06a5072ed2a777ccd5fab5563302a9aa161d6e503685e34",
          "sha1": "af8b58298ba6ffc4e4354ed53c952d5376e4c009",
          "md5": "7a36abec7735548d6e2cb1d4c31882fa"
        }
      ]
    }
  ]
}
