{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.3.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.3.1.jar",
          "url": "builder-8.3.1.jar",
          "size": 13478499,
          "sha512": "1c565682ba96cdd02790d277356250af028445c9d67381126c72c8f67571982cb975059407cb1299802c9bcc9580020806f38281095e341d18f2b47bdda30760",
          "sha256": "8c389417f22bfc2240f353668e46776db66552120504c0f90613df5108616b48",
          "sha1": "cae6313c38e714830b66f049a08d359f895817ed",
          "md5": "f17a88a016a1bc14b156fc13b42b199f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.3.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.3.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.3.1"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.3.1"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.3.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.3.1"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.67"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.67"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.3.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.3.1.jar",
          "url": "builder-8.3.1.jar",
          "size": 13478499,
          "sha512": "1c565682ba96cdd02790d277356250af028445c9d67381126c72c8f67571982cb975059407cb1299802c9bcc9580020806f38281095e341d18f2b47bdda30760",
          "sha256": "8c389417f22bfc2240f353668e46776db66552120504c0f90613df5108616b48",
          "sha1": "cae6313c38e714830b66f049a08d359f895817ed",
          "md5": "f17a88a016a1bc14b156fc13b42b199f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.3.1-javadoc.jar",
          "url": "builder-8.3.1-javadoc.jar",
          "size": 400793,
          "sha512": "679f9d89708452fd431fdec4d3f965391d5b5d70ccef08d711c933f7a191abebbbfdb9582fdb09c96e3a6327f2923461bb18a83bb5bc0747cb44ae3bb530d428",
          "sha256": "adad2581769af3a1fc35c810b04dd22f9041de62016bf854b1346416853054f9",
          "sha1": "72103fdcc5d1893f0f4b00c8ecea6d5747e6e058",
          "md5": "d970ea683015c6fff2d8d78b1caba9c1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.3.1-sources.jar",
          "url": "builder-8.3.1-sources.jar",
          "size": 282328,
          "sha512": "fe244fcaf4b716f74c3785fe9799eb4ab412c00d6788c955022bdf39667c447fa48dbc899020e1f3739d6a85261145498389e87d1e3c5a4c50c94f12d9ff86d5",
          "sha256": "4a0517d07e33030eeefa6179f6158d429ffe4ebb4c33e866ae32df860376a969",
          "sha1": "5fd979221322273ba16db9280d0cc90bad5803e5",
          "md5": "6ca32023b18d350dfe818c7a9ed0dfa5"
        }
      ]
    }
  ]
}
