{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-play-services",
    "version": "1.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.7.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-tasks",
          "version": {
            "requires": "16.0.1"
          },
          "excludes": [
            {
              "group": "com.android.support",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-play-services-1.7.3.jar",
          "url": "kotlinx-coroutines-play-services-1.7.3.jar",
          "size": 13204,
          "sha512": "fecd97f59900f90a0c08b6fe526946f410b80f59395113909869939ed5d797f6c46981d686fab9ed50cfdaa0d754783d3e616ee12b3d167f7cde428b49fdca3b",
          "sha256": "64d6ea1a4d15a2c0950da9a61f49ea7c51268ee74c3b1dddc463e69554441b24",
          "sha1": "7087d47913cfb0062c9909dacbfc78fe44c5ecff",
          "md5": "1f1e1f79a3b4bef6761ab3c0ee704caa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.7.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-tasks",
          "version": {
            "requires": "16.0.1"
          },
          "excludes": [
            {
              "group": "com.android.support",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-play-services-1.7.3.jar",
          "url": "kotlinx-coroutines-play-services-1.7.3.jar",
          "size": 13204,
          "sha512": "fecd97f59900f90a0c08b6fe526946f410b80f59395113909869939ed5d797f6c46981d686fab9ed50cfdaa0d754783d3e616ee12b3d167f7cde428b49fdca3b",
          "sha256": "64d6ea1a4d15a2c0950da9a61f49ea7c51268ee74c3b1dddc463e69554441b24",
          "sha1": "7087d47913cfb0062c9909dacbfc78fe44c5ecff",
          "md5": "1f1e1f79a3b4bef6761ab3c0ee704caa"
        }
      ]
    }
  ]
}
